version: '3.5'

services:

   reverseproxy:
      build:
         context: nginx/
         args:
            DOCKER_HOST: $DOCKER_HOST

   dummyapis:
      build:
         context: epd/
      ports:
         - 8080:8080
